name: RunBenchTest
description: 'Runs a given Benchmark Test'
inputs:
  path:
    description: Path to the performance test
    default: ""
  runName:
    description: Name of the run, for the purpose of file naming and github comments
    default: ""
  githubToken:
    descriptuon: Github secret token to use for commenting on PR
    default: ""
runs:
  using: "composite"
  steps:
    - name: Run Test
      id: test-run
      shell: bash
      run: |
        {
          cd ${{ inputs.path }}
          mkdir output
          go test -tags=test_performance -run=1 -bench=. -count=1 -cpuprofile output/cpu.out -memprofile output/mem.out > output/results.txt
          echo 'OUTPUT<<EOF'
          cat output/results.txt
          echo EOF
        } >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.runName }}
        path: ${{ inputs.path }}/output
    - uses: actions/github-script@v7
      env:
        RESULTS: ${{ steps.test-run.outputs.OUTPUT }}
      with:
        github-token: ${{ inputs.githubToken }}
        script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `# :mag:${{ inputs.runName }}:mag:\nResults of ${{ inputs.runName }} benchmarking testing in \`${{ inputs.path }}\`: \n\`\`\`${process.env.RESULTS}\`\`\``
            })