name: RunPerfTest
description: 'Runs A given Performance Test'
inputs:
  path:
    description: Path to the performance test
    default: ""
  outputName:
    description: Name of the output file
    default: ""
runs:
  using: "composite"
  steps:
    - name: Run Test
      run: |
          cd ${{ inputs.path }}
          mkdir output
          go test -tags=test_performance -run=1 -bench=. -count=1 -cpuprofile output/cpu.out -memprofile output/mem.out > output/results.txt
          cat output/results.txt
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.outputName }}
        path: ${{ inputs.path }}/output