name: "Scheduling Benchmarking"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  before:
    name: Before PR
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/run-bench-test
        with:
            path: pkg/controllers/provisioning/scheduling
            runName: before
            githubToken: ${{ secrets.GITHUB_TOKEN }}
  after:
    name: After PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/run-bench-test
        with:
            path: pkg/controllers/provisioning/scheduling
            runName: after
            githubToken: ${{ secrets.GITHUB_TOKEN }}
  