name: "Scheduling Benchmarking"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  before:
    name: Before PR
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/install-deps
        with:
            path: pkg/controllers/provisioning/scheduling
            outputName: before
  after:
    name: After PR
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/install-deps
        with:
            path: pkg/controllers/provisioning/scheduling
            outputName: after
            commitRef: ${{ github.event.pull_request.head.sha }}